### ISSUE TITLE
Pod to process "execute" workflow jobs is currently missing

### ISSUE THREAD

**Issue by hongaar** [exivity/charts#7]
Execute workflows are currently missing. We should either document this and make changes to API/GUI to reflect this in userland, or come up with an alternative. In SaaS context this should be disabled.

**Comment by timrab** [comment]
+1 we should have this covered. I suggest we also install Powershell and Python on this 'execute' pod. These are the two scripting languages typically being used.

**Comment by ErnstWevers** [comment]
keep in mind that users won't be installing deps with pip in that case

**Comment by ErnstWevers** [comment]
set up a repo at https://github.com/exivity/executor

it has a merlin to listen to the MQ, and has powershell and python3 to handle commands; I'm not sure on how the commands are supplied to the container from merlin?

It will probably need very broad access to Volumes, I imaging all the selection Proximity-api uses minus the logs.

My guess is that it'll require some app config like the other ETL components; but I'm not clear on what that config for merlin is supposed to be.

**Comment by ErnstWevers** [comment]
initial draft
https://github.com/exivity/charts/pull/10

the image definition won't be available until the image is retagged to _docker.io_
